#!/bin/bash
# 使用参考README.md
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_PLATFORM=android-21 \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=false \
-DMNN_USE_SSE=OFF \
-DMNN_BUILD_TEST=OFF \
-DMNN_ARM82=OFF \
-DMNN_KLEIDIAI=OFF \
-DMNN_SME2=OFF \
-DANDROID_ARM_NEON=TRUE \
-DANDROID_STL=c++_shared \
-DMNN_BUILD_OPENCV=ON \
-DMNN_IMGCODECS=ON \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $*

make -j4
mv tools/cv/libMNNOpenCV.so .
